### ISSUE TITLE
Feature: User can  view a list of Races

### ISSUE THREAD

**Issue by Alex-Davis0** [Alex-Davis0/dnd-race-descriptions#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will have the ability to look at a list of the races

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user clicks on race and the races are loaded on the page
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/93169087/148138426-b0255c8c-15bd-4a43-b704-676a3e891652.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x]  Display a list of races when the race nav is  clicked on 
- [ ] 
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
